name: Mark stale issues and pull requests

on:
  schedule:
    - cron: '0 0 * * *' # Runs daily at midnight UTC
  workflow_dispatch:

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - name: Close stale issues and pull requests
        uses: actions/stale@v9
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          stale-issue-message: 'This issue has been automatically marked as stale due to inactivity.'
          stale-pr-message: 'This pull request has been automatically marked as stale due to inactivity.'
          days-before-stale: 60 # Number of days of inactivity before marking an issue/PR as stale
          days-before-close: 7 # Number of days to wait after marking as stale before closing
          stale-issue-label: 'stale'
          stale-pr-label: 'stale'
          exempt-issue-labels: 'pinned, security' # Labels to exempt issues from being marked as stale
          exempt-pr-labels: 'pinned, security' # Labels to exempt PRs from being marked as stale
          only-labels: '' # Only issues/PRs with these labels will be marked as stale
          only-issue-labels: '' # Only issues with these labels will be marked as stale
          only-pr-labels: '' # Only PRs with these labels will be marked as stale
          operations-per-run: 30 # Number of operations per run (to limit API usage)

